openapi: '3.1.0'
info:
  title: FileStorageContextServer
  version: 0.0.0
servers:
  - url: http://{host}:{port}/file-storage-context
    variables:
      host:
        default: 127.0.0.1
      port:
        default: "13579"
        
paths:
  /upload-to-gcs:
    post:
      operationId: uploadToGcs
      parameters:
        - $ref: '#/components/parameters/fileContentType'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
                - meta
              properties:
                file:
                  type: string
                  format: binary
                meta:
                  type: object
                  required:
                    - customerId
                    - documentType
                  properties:
                    customerId:
                      type: string
                    documentType:
                      type: string
                      enum:
                        - ProfitseekingEnterpriseAnnualIncomeTaxReturnDocument
                        - BusinessTaxReturnDocument
                        - BusinessClientRiskControlDocument
                        - FinancialComplianceAuditDocument
                        - TaxComplianceAuditDocument
                        - QuotingProof
                        - ReplyForm
                        - NewBusinessClientRiskControlDocument
            encoding:
              file:
                contentType: application/pdf, image/jpeg, image/png
              meta:
                contentType: application/json
      responses:
        '200':
          description: upload file successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - documentId
                properties:
                  documentId:
                    type: string
                  mediaLink:
                    type: string
        '503':
          $ref: '#/components/responses/ServiceUnavailableError'
                
components:
  parameters:
    fileContentType:
      name: fileContentType
      in: header
      description: file content type
      required: true
      schema:
        type: string
        enum:
          - jpeg
          - png
          - pdf

  responses:
    ServiceUnavailableError:
      description: Service Unavailable (e.g. EventStore error)
      content:
        application/json: {}
