openapi: '3.1.0'
info:
  title: FileStorageContextServer
  version: 0.0.0
servers:
  - url: http://{host}:{port}/file-storage-context
    variables:
      host:
        default: 127.0.0.1
      port:
        default: "13579"
paths:
  /{quotingCaseId}/upload:
    parameters:
      - $ref: '#/components/parameters/quotingCaseId'
    post:
      operationId: uploadReplyForm
      requestBody:
        required: true
        content:
          image/jpeg:
            schema:
              type: string
              format: binary
          image/png:
            schema:
              type: string
              format: binary
          application/pdf:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: upload reply form
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaLink'
        '503':
          $ref: '#/components/responses/ServiceUnavailableError'


components:
  parameters:
    quotingCaseId:
      name: quotingCaseId
      in: path
      description: QuotingCase id to fetch
      required: true
      schema:
        type: string
        
  schemas:
    MediaLink:
      type: object
      properties:
        mediaLink:
          type: string        
          
  responses:
    ServiceUnavailableError:
      description: Service Unavailable (e.g. EventStore error)
      content:
        application/json: {}