openapi: '3.1.0'
info:
  title: FileStorageContextServer
  version: 0.0.0
servers:
  - url: http://{host}:{port}/file-storage-context
    variables:
      host:
        default: 127.0.0.1
      port:
        default: "13579"
        
paths:
  /business-clients:
    post:
      operationId: createBusinessClient
      parameters:
        - $ref: '#/components/parameters/userId'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - customerId
              properties:
                customerId:
                  type: string
      responses:
        '201':
          description: Business client created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessClientId'
        '503':
          $ref: '#/components/responses/ServiceUnavailableError'

  /business-clients/{businessClientId}/upload-profitseeking-enterprise-annual-income-tax-return-document:
    post:
      operationId: uploadProfitseekingEnterpriseAnnualIncomeTaxReturnDocument
      parameters:
        - $ref: '#/components/parameters/businessClientId'
        - $ref: '#/components/parameters/userId'
        - $ref: '#/components/parameters/contentType'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
                - customerId
                - year
              properties:
                file:
                  type: string
                  format: binary
                customerId:
                  type: string
                year:
                  type: number
                  format: double
            encoding:
              customerId:
                contentType: application/json
              year:
                contentType: application/json
             
                
      responses:
        '200':
          description: upload ProfitseekingEnterpriseAnnualIncomeTaxReturnDocument successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - documentId
                properties:
                  documentId:
                    type: string
                  mediaLink:
                    type: string
        '503':
          $ref: '#/components/responses/ServiceUnavailableError'
                
components:
  schemas:
    BusinessClientId:
      type: object
      properties:
        businessClientId:
          type: string

  parameters:
    businessClientId:
      name: businessClientId
      in: path
      required: true
      schema:
        type: string
        
    userId:
      name: userId
      in: header
      description: user id to fetch
      required: true
      schema:
        type: string
        
    contentType:
      name: contentType
      in: header
      description: file content type
      required: true
      schema:
        type: string
        enum:
          - jpeg
          - png
          - pdf

  responses:
    ServiceUnavailableError:
      description: Service Unavailable (e.g. EventStore error)
      content:
        application/json: {}
