# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift-build-testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["6.0"]
        python: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: SwiftyLab/setup-swift@latest
        with:
           swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: |
                  ${{ secrets.DDDKIT_ACCESS_TOKEN }}      
      - run: ulimit -n 10000
      - name: Build and tests
        run: |
          echo ${{ secrets.GCS_CREDENTIALS }} > GCS.cre
          swift test -v --no-parallel
        env:
          GCS_CREDENTIALSFILE: "GCS.cre" 
